version: '3.8'

services:

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - local
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1:
    build:
      context: .
      dockerfile: ApiPayments/DockerfileProd
    container_name: api_instance_1
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - payment-processor
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Local=Host=db;Database=payments_db;Username=db_user;Password=1234
      - "URL_DEFAULT=http://payment-processor-default:8080"
      - "URL_FALLBACK=http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.57"
          memory: "115MB"
  
  api2:
    build:
      context: .
      dockerfile: ApiPayments/DockerfileProd
    container_name: api_instance_2
    restart: always
    ports:
      - "5002:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - payment-processor
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Local=Host=db;Database=payments_db;Username=db_user;Password=1234
      - "URL_DEFAULT=http://payment-processor-default:8080"
      - "URL_FALLBACK=http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.57"
          memory: "115MB"

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d payments_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.21"
          memory: "105MB"

networks:
  local:
    name: local
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data: